### ISSUE TITLE
Request for Access to Pre-trained Model wikiart-1024-stylegan3-t-17.2Mimg.pkl"

### ISSUE THREAD

**Issue by pennypppp** [hywang66/mmist#7]
Hi. Recently, I have been studying the paper Multimodality-guided Image Style Transfer using Cross-modal GAN Inversion (Proceedings of the IEEE/CVF Winter Conference on Applications of Computer Vision, 2024: 4976-4985).

During the process of reproducing the results, I attempted to download the pre-trained model wikiart-1024-stylegan3-t-17.2Mimg.pkl. However, I found the access to the file restricted and could not obtain it through other methods.

Could someone kindly guide me on how to access the model or share any necessary information? I assure you that all the data will be used strictly for research purposes only.

Thank you very much for your help!

**Comment by hywang66** [comment]
Updated. Please try the new link in the readme.
